name: FunEffects
main: lostteam\funeffects\Main
author: Lost Team
version: 1.0.0
api: 1.4.0

commands:
    sick:
          description: Give's a Player Sickness A.K.A Nausea.
          usage: "/sick"
          permission: sick.cmd
